# 服务器开放端口
server:
  port: 20100
  # 压缩,这个属性样板打开了压缩选项，这样稍后应用到JSON正文的压缩就有保证了。
  compression:
    enabled: true
    mime-types: application/json


# 日志
logging.level.org.springframework.security: INFO
logging.file: ./logs/${spring.application.name}.log


# -----Spring Cloud eureka-----
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true                     # docker方式部署需要设置为true
    lease-renewal-interval-in-seconds: 5      # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    lease-expiration-duration-in-seconds: 30  # 等待下一次心跳的超时时间, 默认90s,必须必lease-renewal-interval-in-seconds大
    health-check-url-path: /actuator/health     # 健康检查的地址（依赖spring-boot-starter-actuator）, 2.0后actuator的地址发生了变化
  client:
    registry-fetch-interval-seconds: 5        # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10100/eureka/

# 防止第一次调用失败，设置超时时间为60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

# fegin-ribbon配置, 设置超时,重试等参数
ribbon:
  ReadTimeout: 20000                # 读取超时20秒
  ConnectTimeout: 20000             # 链接超时20秒
  MaxAutoRetries: 2                 # 当前实例重试次数
  MaxAutoRetriesNextServer: 2      # 下一个实例重试次数
  OkToRetryOnAllOperations: true   # 对所有操作请求都进行重试


# spring-boot-admin 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


# 链路跟踪配置 sleuth & zipkin
spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0                # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/   # 指定 Zipkin 服务器的地址, 默认localhost:9411
    #sender.type: kafka                 # 数据到第三方配置
