# 服务器开放端口
server:
  port: 10000

# 整合异构语言, 端口
sidecar:
  port: 8000

spring:
  # AOP
  aop:
    proxy-target-class: true
    auto: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true                 # docker方式部署需要设置为true
    lease-renewal-interval-in-seconds: 5  # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.82.64:20000/eureka/

# 防止第一次调用失败，设置超时时间为60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 20000                # 读取超时20秒
  ConnectTimeout: 20000             # 链接超时20秒
  MaxAutoRetries: 2                 # 当前实例重试次数
  MaxAutoRetriesNextServer: 2      # 下一个实例重试次数
  OkToRetryOnAllOperations: true   # 对所有操作请求都进行重试

zuul:
  add-host-header: true             # 必须加上，否则有跨域问题
  add-proxy-headers: true
  host:
    connect-timeout-millis: 20000   # 超时时间
    socket-timeout-millis: 20000    # socket超时时间
  routes:
    dr-api-server: /api/**
    dr-auth-server: /auth/**
    dr-boss-server: /boss/**
    dr-calculate-server: /calculate/**
    dr-consumer-server: /consumer/**
    dr-marketing-server: /marketing/**
    dr-message-server: /message/**
    dr-order-server: /order/**
    dr-partner-server: /partner/**
    dr-payment-server: /payment/**
    dr-store-server: /store/**
    dr-minimarketing-server: /mini-marketing/**


darren-clud:

  # 不做权限校验的url，格式符合AntPathMatcher规范，认证中心、消费者服务不需要鉴权
  pass-urls: >
    /**/open/**,
    /**/auth/**,
    /**/druid/**

  # 只需登陆即放行，格式符合AntPathMatcher规范，消息服务配置不需要鉴权
  pass-login-urls: >
    /**/noauth/**,
    /loginout/*