# 服务器开放端口
server:
  port: 20100

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true                 # docker方式部署需要设置为true
    lease-renewal-interval-in-seconds: 5  # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
    health-check-url-path: /actuator/health # 健康检查的地址（依赖spring-boot-starter-actuator）, 2.0后actuator的地址发生了变化
  client:
    registry-fetch-interval-seconds: 5    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.82.64:20000/eureka/

# 防止第一次调用失败，设置超时时间为60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 20000                # 读取超时20秒
  ConnectTimeout: 20000             # 链接超时20秒
  MaxAutoRetries: 2                 # 当前实例重试次数
  MaxAutoRetriesNextServer: 2      # 下一个实例重试次数
  OkToRetryOnAllOperations: true   # 对所有操作请求都进行重试

# spring-boot-admin 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS