
server:
  port: 10100

# 日志
logging.level.org.springframework.security: INFO
logging.file: ./logs/${spring.application.name}.log

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true # 注册时使用ip而不是主机名, docker方式部署需要设置为true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: false # 表示是否将自己注册到Eureka Server,默认为true.由于当前应用就是Eureka Server,故而设置为false.
    fetch-registry: false        # 表示是否从Eureka Server获取注册信息,默认为true.因为这是一个单点的Eureka Server,不需要同步其他的Eureka Server节点的数据,这里设置为false
    service-url:
      # 设置与Eureka Server的地址,查询服务和注册服务都需要依赖这个地址.默认是http://localhost:8761/eureka/;多个地址可使用','风格.
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false       # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 10000  # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    wait-time-in-ms-when-sync-empty: 0

# 注册中心安全配置
spring:
  security:
    user:
      name: admin
      password: 123456

# spring-boot-actuator模块提供监控端点权限
spring:
  management:
    security:
      enabled: false
